version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@tensorflow/tfjs"
    versions:
    - 2.8.6
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
    - 3.4.0
    - 3.5.0
  - dependency-name: connect-mongo
    versions:
    - 4.1.0
    - 4.2.0
    - 4.2.2
    - 4.3.0
    - 4.3.1
    - 4.4.0
